### ISSUE TITLE
run with explicit options

### ISSUE THREAD

**Issue by jelc** [vvendigo/impostor#12]
similar as apache server, to run more instances on different ports.
for example: ./server.py /path/my_options.json

**Comment by vvendigo** [comment]
Done already:
    $ ./server.py --help
    Usage: server.py [options] [host][:port] [rootDir]

```
Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -f CONF, --config=CONF
                        JSON server config file to use
```
